# This workflow validates, deploys, and runs the specified bundle
# within a pre-production target named "dev".
name: "bronze_to_silver_country_indices_job"

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - dev-main

jobs:
  deploy:
    name: "Deploy bundle"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@main

      # Add this step to list all files and directories recursively
      - run: |
          echo "Listing all files in the working directory:"
          ls -R
      - run: databricks bundle deploy
        working-directory: ./era5-daily/02_Bronze_to_Silver_Country_Indices/bronze_to_silver_country_indices
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_DATA_ENGINEERING_TOKEN }}
          DATABRICKS_BUNDLE_ENV: dev

  pipeline_update:
    name: "Run pipeline update"
    runs-on: ubuntu-latest
    needs:
      - deploy

    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@main

      # Add this step to list all files and directories recursively before running the bundle
      - run: |
          echo "Listing all files in the working directory:"
          ls -R
      - run: databricks bundle run  bronze_to_silver_country_indices_job --refresh-all
        working-directory: ./era5-daily/02_Bronze_to_Silver_Country_Indices/bronze_to_silver_country_indices
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_DATA_ENGINEERING_TOKEN }}
          DATABRICKS_BUNDLE_ENV: dev
