# GitHub Actions Workflow for bronze_to_silver_country_indices_job

name: "Bronze to Silver Country Indices Workflow"

on:
  pull_request:
    branches:
      - dev-main

jobs:
  deploy_bronze_to_silver_country_indices:
    name: "Deploy Bronze to Silver Country Indices Job"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@main

      - run: databricks bundle deploy
        working-directory: ./era5-daily/02_Bronze_to_Silver_Country_Indices/bronze_to_silver_country_indices
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_DATA_ENGINEERING_TOKEN }}
          DATABRICKS_BUNDLE_ENV: dev

  run_bronze_to_silver_country_indices:
    name: "Run Bronze to Silver Country Indices Job"
    runs-on: ubuntu-latest
    needs:
      - deploy_bronze_to_silver_country_indices

    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@main

      - run: |
          databricks jobs run-now --job-id bronze_to_silver_country_indices_job --notebook-params '
          {
            "unit_tests_task": {
              "notebook_path": "../tests/bronze-to-silver-countryindices-run-unit-test.py"
            },
            "unit_tests_task_2": {
              "notebook_path": "../tests/df-tessellate-bronze-to-silver-countryindices-run-unit-test.py"
            },
            "ingest_countries": {
              "notebook_path": "../src/01_Ingest_Countries.py"
            },
            "validate_countries": {
              "notebook_path": "../src/02_Validate_Countries.py"
            },
            "tessellate_countries": {
              "notebook_path": "../src/03_Tessellate_Countries.py"
            },
            "viz_countries": {
              "notebook_path": "../src/04_Viz_Countries.py"
            },
            "union_chips": {
              "notebook_path": "../src/05_Union_Chips.py"
            }
          }'
        working-directory: ./era5-daily/02_Bronze_to_Silver_Country_Indices/bronze_to_silver_country_indices
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_DATA_ENGINEERING_TOKEN }}
          DATABRICKS_BUNDLE_ENV: dev
