name: "Deploy and Run Combined ERA5 Workflow"

on:
  push:
    branches:
      - production
      - development
      - 'feature/**'

jobs:
  deploy_and_run_combined_job:
    name: "Deploy and Run Combined ERA5 Jobs"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install yq
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip install yq
        run: pip install yq

      - name: Update databricks.yml file
        working-directory: ./era5-daily/Combined_Run
        # set the pipeline mode to be the name of the branch
        run: |
          yq ".targets.era5_pipeline.mode = \"${GITHUB_REF_NAME}\"" databricks.yml -yi
          cat databricks.yml

      # Step 3: Deploy the Databricks Bundle
      - name: Deploy Databricks Bundle
        uses: databricks/setup-cli@main
        working-directory: ./era5-daily/Combined_Run
        run: |
          databricks bundle deploy --target era5_pipeline
        env:
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}

      # # Step 4: Run the Job Using Databricks Bundle Command
      # - name: Run the Deployed Job Without Tracking
      #   working-directory: ./era5-daily/Combined_Run
      #   run: |
      #     databricks bundle run uber_job --no-wait
      #   env:
      #     DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_DEVELOPMENT }}
      #     DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
      #     DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
