name: "Deploy and Run Combined ERA5 Workflow"

on:
  push:
    branches:
      - production
      - development
      - 'feature/**'

jobs:
  deploy_and_run_combined_job:
    name: "Deploy and Run Combined ERA5 Jobs"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up the Databricks CLI
        uses: databricks/setup-cli@main

      - name: Execution Environment
        run: |
          sudo apt-get update && sudo apt-get install -y yq

      - name: Set Deployment Mode
        id: set_mode
        run: |
          if [[ "$GITHUB_REF_NAME" == feature/* ]]; then
            echo "MODE=test" >> $GITHUB_ENV
          else
            echo "MODE=$GITHUB_REF_NAME" >> $GITHUB_ENV
          fi
          echo "Branch: $GITHUB_REF_NAME"
          echo "Mode: $MODE"

      - name: Update databricks.yml file
        working-directory: ./era5-daily/Combined_Run
        run: |
          yq ".targets.era5_pipeline.mode = \"${MODE}\"" -i databricks.yml
      # - name: Deploy to Databricks
      #   run: |
      #     databricks deploy --config databricks.yml


      # # Step 3: Deploy the Databricks Bundle
      # - name: Deploy Databricks Bundle
      #   working-directory: ./era5-daily/Combined_Run
      #   run: |
      #     databricks bundle deploy
      #   env:
      #     DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_DEVELOPMENT }}
      #     DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
      #     DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}

      # # Step 4: Run the Job Using Databricks Bundle Command
      # - name: Run the Deployed Job Without Tracking
      #   working-directory: ./era5-daily/Combined_Run
      #   run: |
      #     databricks bundle run uber_job --no-wait
      #   env:
      #     DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_DEVELOPMENT }}
      #     DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
      #     DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
