# Combined ERA5 Workflow

name: "Combined ERA5 Workflow"

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - dev-main

jobs:
  # Job 1: era5_dev_source_to_staging_job
  deploy_era5_source_to_staging:
    name: "Deploy era5_dev_source_to_staging_job"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@v1

      - run: databricks bundle deploy
        working-directory: ./era5-daily/Combined_Run/combined_run
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_DATA_ENGINEERING_TOKEN }}
          DATABRICKS_BUNDLE_ENV: dev

  run_era5_source_to_staging:
    name: "Run era5_dev_source_to_staging_job"
    runs-on: ubuntu-latest
    needs:
      - deploy_era5_source_to_staging

    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@v1

      - run: databricks bundle run era5_dev_source_to_staging_job --refresh-all
        working-directory: ./era5-daily/Combined_Run/combined_run
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_DATA_ENGINEERING_TOKEN }}
          DATABRICKS_BUNDLE_ENV: dev

  # Job 2: era5_dev_source_to_bronze_country_boundaries_job
  deploy_era5_source_to_bronze_country_boundaries:
    name: "Deploy era5_dev_source_to_bronze_country_boundaries_job"
    runs-on: ubuntu-latest
    needs:
      - run_era5_source_to_staging

    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@v1

      - run: databricks bundle deploy
        working-directory: ./era5-daily/Combined_Run/combined_run
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_DATA_ENGINEERING_TOKEN }}
          DATABRICKS_BUNDLE_ENV: dev

  run_era5_source_to_bronze_country_boundaries:
    name: "Run era5_dev_source_to_bronze_country_boundaries_job"
    runs-on: ubuntu-latest
    needs:
      - deploy_era5_source_to_bronze_country_boundaries

    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@v1

      - run: databricks bundle run era5_dev_source_to_bronze_country_boundaries_job --refresh-all
        working-directory: ./era5-daily/Combined_Run/combined_run
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_DATA_ENGINEERING_TOKEN }}
          DATABRICKS_BUNDLE_ENV: dev

  # Job 3: era5_dev_staging_to_bronze_job
  deploy_era5_staging_to_bronze:
    name: "Deploy era5_dev_staging_to_bronze_job"
    runs-on: ubuntu-latest
    needs:
      - run_era5_source_to_bronze_country_boundaries

    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@v1

      - run: databricks bundle deploy
        working-directory: ./era5-daily/Combined_Run/combined_run
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_DATA_ENGINEERING_TOKEN }}
          DATABRICKS_BUNDLE_ENV: dev

  run_era5_staging_to_bronze:
    name: "Run era5_dev_staging_to_bronze_job"
    runs-on: ubuntu-latest
    needs:
      - deploy_era5_staging_to_bronze

    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@v1

      - run: databricks bundle run era5_dev_staging_to_bronze_job --refresh-all
        working-directory: ./era5-daily/Combined_Run/combined_run
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_DATA_ENGINEERING_TOKEN }}
          DATABRICKS_BUNDLE_ENV: dev

  # Job 4: era5_bronze_to_silver_country_indices_job
  deploy_era5_bronze_to_silver_country_indices:
    name: "Deploy era5_bronze_to_silver_country_indices_job"
    runs-on: ubuntu-latest
    needs:
      - run_era5_staging_to_bronze

    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@v1

      - run: databricks bundle deploy
        working-directory: ./era5-daily/Combined_Run/combined_run
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_DATA_ENGINEERING_TOKEN }}
          DATABRICKS_BUNDLE_ENV: dev

  run_era5_bronze_to_silver_country_indices:
    name: "Run era5_bronze_to_silver_country_indices_job"
    runs-on: ubuntu-latest
    needs:
      - deploy_era5_bronze_to_silver_country_indices

    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@v1

      - run: databricks bundle run era5_bronze_to_silver_country_indices_job --refresh-all
        working-directory: ./era5-daily/Combined_Run/combined_run
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_DATA_ENGINEERING_TOKEN }}
          DATABRICKS_BUNDLE_ENV: dev

  # Job 5: era5_bronze_to_silver_approximate_join_job
  deploy_era5_bronze_to_silver_approximate_join:
    name: "Deploy era5_bronze_to_silver_approximate_join_job"
    runs-on: ubuntu-latest
    needs:
      - run_era5_bronze_to_silver_country_indices

    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@v1

      - run: databricks bundle deploy
        working-directory: ./era5-daily/Combined_Run/combined_run
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_DATA_ENGINEERING_TOKEN }}
          DATABRICKS_BUNDLE_ENV: dev

  run_era5_bronze_to_silver_approximate_join:
    name: "Run era5_bronze_to_silver_approximate_join_job"
    runs-on: ubuntu-latest
    needs:
      - deploy_era5_bronze_to_silver_approximate_join

    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@v1

      - run: databricks bundle run era5_bronze_to_silver_approximate_join_job --refresh-all
        working-directory: ./era5-daily/Combined_Run/combined_run
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_DATA_ENGINEERING_TOKEN }}
          DATABRICKS_BUNDLE_ENV: dev

  # Job 6: era5_bronze_to_silver_strict_join_job
  deploy_era5_bronze_to_silver_strict_join:
    name: "Deploy era5_bronze_to_silver_strict_join_job"
    runs-on: ubuntu-latest
    needs:
      - run_era5_bronze_to_silver_approximate_join

    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@v1

      - run: databricks bundle deploy
        working-directory: ./era5-daily/Combined_Run/combined_run
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_DATA_ENGINEERING_TOKEN }}
          DATABRICKS_BUNDLE_ENV: dev

  run_era5_bronze_to_silver_strict_join:
    name: "Run era5_bronze_to_silver_strict_join_job"
    runs-on: ubuntu-latest
    needs:
      - deploy_era5_bronze_to_silver_strict_join

    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@v1

      - run: databricks bundle run era5_bronze_to_silver_strict_join_job --refresh-all
        working-directory: ./era5-daily/Combined_Run/combined_run
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_DATA_ENGINEERING_TOKEN }}
          DATABRICKS_BUNDLE_ENV: dev
