name: "Deploy and Run Combined ERA5 Workflow"

on:
  push:
    branches:
      - production
      - development
      - 'feature/**'

jobs:
  deploy_and_run_combined_job:
    name: "deploy and run combined era5 jobs"
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: setup databricks cli
        uses: databricks/setup-cli@main

      - name: determine DAB mode production/development
        run: |
          if [[ "$GITHUB_REF_NAME" == "production" ]]; then
            echo "MODE=production" >> $GITHUB_ENV
          else
            echo "MODE=development" >> $GITHUB_ENV
          fi

      - name: Validate DAB
        working-directory: ./era5-daily/Combined_Run
        run: |
          databricks bundle validate --target $MODE

      - name: Deploy DAB
        working-directory: ./era5-daily/Combined_Run
        run: |
          databricks bundle deploy --target $MODE
        env:
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}

      - name: Run the job once
        working-directory: ./era5-daily/Combined_Run
        run: |
          databricks bundle run --target $MODE
        env:
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
