name: "Deploy and Run Combined ERA5 Workflow"

on:
  push:
    branches:
      - production
      - development
      - 'feature/**'

jobs:
  deploy_and_run_combined_job:
    name: "deploy and run combined era5 jobs"
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: setup databricks cli
        uses: databricks/setup-cli@main

      - name: install yq  # used to dynamically edit our databricks.yml file
        run: pip install yq

      - name: determine dab pipeline mode
        run: |
          if [[ "$GITHUB_REF_NAME" == "production" ]]; then
            echo "MODE=production" >> $GITHUB_ENV
          else
            echo "MODE=development" >> $GITHUB_ENV
          fi
      - name: update databricks.yml file
        working-directory: ./era5-daily/Combined_Run
        run: |
          yq ".targets.era5_pipeline.mode = \"${MODE}\"" databricks.yml -yi
          cat databricks.yml
      - name: Deploy DAB
        working-directory: ./era5-daily/Combined_Run
        run: |
          databricks bundle deploy
        env:
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}

      # - name: Run the Deployed Job Without Tracking
      #   working-directory: ./era5-daily/Combined_Run
      #   run: |
      #     databricks bundle run era5_01_source_to_staging_job
      #   env:
      #     DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
      #     DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
