name: Run Unit Tests (Data Engineering)

on:
  pull_request:
    branches:
      - dev-main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install xarray
        pip install netCDF4 h5netcdf
        pip install dask   
        pip install rioxarray
        pip install tqdm

    - name: Run Unit Tests
      run: |
        python unit-test.py
